### ISSUE TITLE
Api Retorna Json Vazio

### ISSUE THREAD

**Issue by bergpb** [rodrigorf/filmes-cartaz-json#1]
Realizei o clone da aplicação na minha máquina e ao consultar a rota da api a mesma retornou um json vazio:

{
  "filmes": [
    
  ]
}

Provavelmente o html da página em questão foi modificado, estarei olhando essa semana se consigo corrigir e envio um pull-request para o projeto.
E parabéns pelo tutorial ótimo para quem está começando com o flask.

**Comment by rodrigorf** [comment]
Verdade @bergpb, fui verificar agora também e vi que não trouxe a lista de filmes, acredito que até mês passado estava ok mas de tempos em tempos eles mudam algo e acaba quebrando o código. Vou dar uma olhada também nessa issue e se puder adianto. 

Agradeço a ajuda e se tiver ideias manda ai. Seria interessante termos crawlers para outros sites também que possuam lista de filmes.

**Comment by rodrigorf** [comment]
@bergpb fiz a correção, felizmente foi apenas uma class que removeram da div que contém a lista de filmes:

Estava assim: 
`for dataBox in soup.find_all("div", class_="card card-entity card-entity-list cf hred"):`

Agora esta assim:
`for dataBox in soup.find_all("div", class_="card card-entity card-entity-list cf"):`

**Comment by rodrigorf** [comment]
To encerrando essa issue, testei novamente hoje e está ok. Qualquer coisa cria outro registro. 👍
